name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

  docker-build:
    needs: tests  # Attend que le job 'tests' réussisse
    runs-on: ubuntu-latest
    if: github.event_name == 'push'  # Ne se déclenche pas sur les PRs
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/flaskapp .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/flaskapp ${{ secrets.DOCKER_USERNAME }}/flaskapp:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/flaskapp:latest
